{% set version = "1.4.2" %}

package:
  name: geotiff
  version: {{ version }}

source:
  url: http://download.osgeo.org/geotiff/libgeotiff/libgeotiff-{{ version }}.tar.gz
  sha256: ad87048adb91167b07f34974a8e53e4ec356494c29f1748de95252e8f81a5e6e

build:
  number: 1
  skip: True  # [win and py36]
  features:
    - vc9  # [win and py27]
    - vc14  # [win and (py35 or py36)]

requirements:
  build:
    - python  # [win]
    - cmake
    - toolchain
    - proj4 4.9.3
    - zlib 1.2.11
    - jpeg 9*
    - libtiff >=4.0.3,<4.0.8
    - vc 9  # [win and py27]
    - vc 14  # [win and (py35 or py36)]

  run:
    - proj4 4.9.3
    - zlib 1.2.11
    - jpeg 9*
    - libtiff >=4.0.3,<4.0.8
    - vc 9  # [win and py27]
    - vc 14  # [win and (py35 or py36)]

test:
  commands:
    - test -f $PREFIX/lib/libgeotiff.so  # [linux]
    - test -f $PREFIX/lib/libgeotiff.dylib  # [osx]
    - if not exist %LIBRARY_LIB%\\geotiff_i.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\geotiff.dll exit 1  # [win]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://trac.osgeo.org/geotiff
  license: MIT
  license_file: LICENSE
  summary: 'TIFF based interchange format for georeferenced raster imagery'
  description: |
    GeoTIFF represents an effort by over 160 different remote sensing,
    GIS, cartographic, and surveying related companies and organizations
    to establish a TIFF based interchange format for georeferenced raster imagery.

extra:
  recipe-maintainers:
    - gillins
    - ocefpaf
