appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: yCGg2sM0hHFAqrZ00zqEUQn6bFQ1xDvQtc8NtrpSFMzRizsWwiY0NPHnayoqGKuD8IIZVT0jKFaN2XuUPg4V3VXJB2+cukC2pI/nbvd4W+nVUiB+2eQWxddIthNfxgedDckL6JfCNw47IpOATRVJsrQgJTydAOlWAw8pQWJt5LxYkY19OA1zCTX7sMmnXpJSUTLIPeFdUGcSnm7HjTzyicJ1CTXL5/2g7XLQaJP9Y6grtRWDTtukUzQjtrCY/qc5GHKtrr9tgUmeyKtlkNFVpd94Y8LlrcJ5DmFe4xAYtdjKW101kOTH9QCA44fpPwRsdL8AI/hqDXdw6rQkHhdT9Zonoohl08bopvNSx/whygsmnCLPyafbTo/d/LY/Bv+9ZkK52fn46QGLSoRJhjLP8Zh8a55Q8VQmJ+BKMcHB7SSPWa3zvvX9FmHy8zqNAl3L4O7ZZRslmEh5QnW4PYN7VPdSxDlgPP5mzbroBIBmwExUezvWfBhc38gp1Fg7KGgrsBRqI/NrP9b19aylNXWh43+/QAjWghN4QsOOjtyR74OwWXo1+5rsye6vmiMn/brMrjwTjNe/d8QMSAHjLWa59SPzvSsu2gC0MPOF4Rq7W94VhOHVFMdEal5ryr3XYFNDfdo5yiQ+bZ6hpDQzXiqk/RhLpd212jk76CDY0fm/O5A=}
provider:
  win: azure
